name: Build and Push Docker Images

on:
  push:
    tags:
      - '*.*.*'

env:
  PRODUCT_NAME: juce-build-windows
  BASE_IMAGE: mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
  BASE_IMAGE_FILE: windowsservercore.tar

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Restore base image cache
      id: cache-builder-image
      uses: actions/cache@v3
      with:
        path: ${{ env.BASE_IMAGE_FILE }}
        key: ${{ env.BASE_IMAGE }}

    - name: Pull base image
      if: steps.cache-builder-image.outputs.cache-hit != 'true'
      shell: bash
      run: |
        docker login \
          --username ${{ github.repository_owner }} \
          --password ${{ secrets._GITHUB_PAT }} \
          ghcr.io

        docker pull ${{ env.BASE_IMAGE }}

        docker save \
          -o ${{ env.BASE_IMAGE_FILE }} \
          ${{ env.BASE_IMAGE }}

    - name: Load base image cache
      if: steps.cache-builder-image.outputs.cache-hit == 'true'
      shell: bash
      run: |
        docker load -i ${{ env.BASE_IMAGE_FILE }}

    - name: Build image
      shell: bash
      run: |
        tag="ghcr.io/${{ github.repository }}/${{ env.PRODUCT_NAME }}:${{ github.ref_name }}"

        docker build \
          --file=./Dockerfile \
          --tag="${tag,,}" \
          .

    - name: Push image
      shell: bash
      run: |
        tag="ghcr.io/${{ github.repository }}/${{ env.PRODUCT_NAME }}:${{ github.ref_name }}"
        docker push "${tag,,}"
